// Generated by tools/generate-sounds.js — do not edit by hand.
// Run `node tools/generate-sounds.js` to regenerate.

import Foundation

public enum SoundCategory: String, CaseIterable, Codable, Sendable, Identifiable {
    case bright = "bright"
    case noisy = "noisy"
    case energetic = "energetic"
    case calm = "calm"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .bright: return "Bright"
        case .noisy: return "Noisy"
        case .energetic: return "Energetic"
        case .calm: return "Calm"
        }
    }

    public var symbolName: String {
        switch self {
        case .bright: return "music.note"
        case .noisy: return "light.beacon.max.fill"
        case .energetic: return "flame.fill"
        case .calm: return "cup.and.saucer.fill"
        }
    }
}

public struct AlarmTone: Identifiable, Hashable, Sendable {
    public let id: String
    public let name: String
    public let category: SoundCategory
    /// File name including extension. Bundled tones resolve out of the app
    /// bundle; imported ones resolve out of the custom sounds directory.
    public let fileName: String
    /// True for audio the user imported themselves.
    public let isCustom: Bool

    public init(
        id: String,
        name: String,
        category: SoundCategory,
        fileName: String? = nil,
        isCustom: Bool = false
    ) {
        self.id = id
        self.name = name
        self.category = category
        self.fileName = fileName ?? "\(id).wav"
        self.isCustom = isCustom
    }
}

public enum SoundCatalog {
    /// Duration of every bundled tone, in seconds. Kept under the 30 s limit
    /// that `UNNotificationSound` enforces.
    public static let toneDuration: TimeInterval = 28

    /// Near-silent loop used to hold the audio session alive in the background.
    public static let keepAliveFileName = "keepalive.wav"

    public static let all: [AlarmTone] = [
        AlarmTone(id: "air_raid", name: "Air Raid", category: .noisy),
        AlarmTone(id: "police_siren", name: "Police Siren", category: .noisy),
        AlarmTone(id: "fire_alarm", name: "Fire Alarm", category: .noisy),
        AlarmTone(id: "klaxon", name: "Klaxon", category: .noisy),
        AlarmTone(id: "emergency_broadcast", name: "Emergency Broadcast", category: .noisy),
        AlarmTone(id: "nuclear_alert", name: "Nuclear Alert", category: .noisy),
        AlarmTone(id: "red_alert", name: "Red Alert", category: .noisy),
        AlarmTone(id: "foghorn", name: "Foghorn", category: .noisy),
        AlarmTone(id: "battle_stations", name: "Battle Stations", category: .noisy),
        AlarmTone(id: "radar", name: "Radar", category: .bright),
        AlarmTone(id: "beacon", name: "Beacon", category: .bright),
        AlarmTone(id: "chimes", name: "Chimes", category: .bright),
        AlarmTone(id: "bulletin", name: "Bulletin", category: .energetic),
        AlarmTone(id: "waves", name: "Waves", category: .bright),
        AlarmTone(id: "ascending", name: "Ascent", category: .energetic),
        AlarmTone(id: "digital_beep", name: "3000", category: .energetic),
        AlarmTone(id: "retro_arcade", name: "Retro Arcade", category: .energetic),
        AlarmTone(id: "pulse", name: "Momentum", category: .energetic),
        AlarmTone(id: "blip_ladder", name: "City Rush", category: .energetic),
        AlarmTone(id: "data_alert", name: "Motion", category: .energetic),
        AlarmTone(id: "sunrise", name: "Sunrise", category: .calm),
        AlarmTone(id: "music_box", name: "Music Box", category: .calm),
        AlarmTone(id: "soft_bells", name: "Soft Bells", category: .calm),
        AlarmTone(id: "harp", name: "Harp", category: .calm),
        AlarmTone(id: "morning_dew", name: "Morning Dew", category: .calm),
        AlarmTone(id: "rooster", name: "Rooster", category: .bright),
        AlarmTone(id: "birds", name: "Birdsong", category: .bright),
        AlarmTone(id: "ocean", name: "Tide", category: .calm),
        AlarmTone(id: "sunbeam", name: "Sunbeam", category: .bright),
        AlarmTone(id: "skyline", name: "Skyline", category: .bright),
        AlarmTone(id: "overdrive", name: "Overdrive", category: .energetic),
        AlarmTone(id: "marathon", name: "Marathon", category: .energetic),
    ]

    public static let defaultToneID = "air_raid"

    public static func tone(id: String) -> AlarmTone {
        all.first { $0.id == id } ?? all.first { $0.id == defaultToneID } ?? all[0]
    }

    public static func tones(in category: SoundCategory) -> [AlarmTone] {
        all.filter { $0.category == category }
    }

    /// Backing store for the "Random" entry at the top of each category, which
    /// picks a different tone every time the alarm fires so you never
    /// habituate to one sound.
    public static func randomTone(in category: SoundCategory, excluding excluded: String? = nil) -> AlarmTone {
        let pool = tones(in: category)
        let filtered = pool.filter { $0.id != excluded }
        return (filtered.isEmpty ? pool : filtered).randomElement() ?? all[0]
    }
}

// MARK: - Sleep sounds

public struct SleepSound: Identifiable, Hashable, Sendable {
    public let id: String
    public let name: String
    public let symbolName: String

    public var fileName: String { "\(id).wav" }
}

public enum SleepSoundCatalog {
    public static let all: [SleepSound] = [
        SleepSound(id: "ocean_wave", name: "Ocean wave", symbolName: "water.waves"),
        SleepSound(id: "campfire", name: "Campfire", symbolName: "flame"),
        SleepSound(id: "rainy_thunder", name: "Rainy thunder", symbolName: "cloud.bolt.rain"),
        SleepSound(id: "forest_crickets", name: "Forest crickets", symbolName: "leaf"),
        SleepSound(id: "light_rain", name: "Light rain", symbolName: "cloud.rain"),
    ]

    /// Minutes the bedtime player runs before fading out. 0 means "until the
    /// alarm rings".
    public static let durationOptions: [Int] = [5, 10, 15, 30, 45, 60, 90, 0]

    public static func sound(id: String?) -> SleepSound? {
        guard let id else { return nil }
        return all.first { $0.id == id }
    }
}
